spring:
  application:
    name: wallet-transfer
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet}
    username: ${SPRING_DATASOURCE_USERNAME:wallet}
    password: ${SPRING_DATASOURCE_PASSWORD:wallet}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.kullu.wallet: DEBUG
